spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sbms28
    username: root
    password: "Nivas@2001"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 200

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect